language: generic
sudo: required
services:
  - docker

before-install:
  # - docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t michaladorno/test-container -f Dockerfile.dev .
  - docker push michaladorno/test-container
script:
  - docker run -it -e CI=true michaladorno/test-container npm run test -- --coverage

