language: generic
sudo: required
services:
  - docker
git:
  depth: false
script:
  # - docker login -u "$DOCKER_USERNAME" -p $DOCKER_PASSWORD
  - docker build -t "$DOCKER_USERNAME"/test-container -f Dockerfile.dev .
  - docker images -a
  - docker ps -a
  - docker run -it -e CI=true -p 8080:80 "$DOCKER_USERNAME"/test-container npm run test -- --coverage

